// src/components/Profile.svelte
<script>
  import { onMount } from "svelte";

  $: profileUrl = "";

  async function getProfileFromGitHub() {
    const res = await fetch("https://api.github.com/users/bloodzmoon");
    const data = await res.json();
    profileUrl = data.avatar_url;
  }

  onMount(getProfileFromGitHub);
</script>

<section class="profile-section">
  <img src={profileUrl} class="img" alt="profile" />
  <div class="title">
    <p class="name">Thanyathon Pornsawatchai</p>
    <p class="role">Software developer</p>
  </div>
</section>

<style>
  .profile-section {
    margin-top: 6rem;
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .img {
    --size: 240px;
    border-radius: 50%;
    width: var(--size);
    height: var(--size);
    position: relative;
  }

  .title {
    text-align: center;
  }

  .name {
    font-size: 2rem;
    font-weight: 400;
  }

  .role {
    color: #0088eb;
    font-size: 2rem;
    margin-top: -2rem;
  }

  @media only screen and (max-width: 500px) {
    .name,
    .role {
      font-size: 1.5rem;
    }
  }
</style>

// src/components/Repo/Profile.vue
<template>
  <section class="profile">
    <router-link to="/" class="back-icon">
      <unicon name="angle-left" fill="#75a2da" width="36" height="36" />
      <span class="m-hide">Back</span>
    </router-link>
    <img class="profile-img" :src="profile.avatar_url" />
    <span class="name">{{ profile.name }}</span>
    <a class="mention" :href="profile.html_url" target="_blank">@{{ profile.login }}</a>
    <span class="joined">Joined {{ joinedDate }}</span>
  </section>
</template>

<script>
export default {
  name: 'Profile',
  props: {
    profile: Object,
  },
  computed: {
    joinedDate: function () {
      const date = new Date(this.profile.created_at)
      const options = { day: 'numeric', month: 'long', year: 'numeric' }
      return date.toLocaleDateString('en-US', options)
    },
  },
}
</script>

<style scoped>
.back-icon {
  color: #75a2da;
  position: absolute;
  top: 5%;
  left: 5%;
  font-size: 22px;
  display: flex;
  align-items: center;
  text-decoration: none;
  opacity: 0.6;
  transition: 0.2s;
}

.back-icon:hover {
  opacity: 1;
}

.m-hide {
  transform: translateY(-3.5px);
}

.profile {
  width: 100%;
  height: 480px;
  color: white;
  background: #1a1e22;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  position: relative;
}

.profile-img {
  width: 180px;
  height: 180px;
  background: darkslategray;
  border-radius: 50%;
  border: 4px solid #26aefd;
  display: block;
  margin: 20px;
}

.name {
  text-align: center;
  font-size: 36px;
  margin: 10px;
}

.mention {
  text-decoration: none;
  color: #26aefd;
  font-size: 24px;
}

.joined {
  color: rgb(149, 155, 175);
  font-size: 18px;
  margin: 20px;
}

@media screen and (max-width: 450px) {
  .m-hide {
    display: none;
  }
}
</style>
